apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hackathon-backend
  namespace: alien-legacy-500702-r7
  labels:
    cloud.googleapis.com/location: asia-northeast1
spec:
  template:
    spec:
      serviceAccountName: hackathon-runner@alien-legacy-500702-r7.iam.gserviceaccount.com
      containers:
        # Ingress 主容器：Node.js API
        - image: asia-northeast1-docker.pkg.dev/alien-legacy-500702-r7/hackathon-repo/api@sha256:8a912c298911efc96e20d650bef0e1563484b872b083f0caa3594a8d7eed7d42
          name: backend-api
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: AGENT_API_URL
              value: "http://127.0.0.1:7668"
            - name: GCS_BUCKET_NAME
              value: "hackathon-applets-500702-r7"
            - name: FIREBASE_PROJECT_ID
              value: "alien-legacy-500702-r7"
            - name: GOOGLE_CLOUD_PROJECT
              value: "alien-legacy-500702-r7"
            - name: APP_URL
              value: "https://hackathon-web-498706-asia-northeast1.a.run.app"
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hackathon-master-key
                  key: latest
        # Sidecar 伴生容器：Python Agent
        - image: asia-northeast1-docker.pkg.dev/alien-legacy-500702-r7/hackathon-repo/agent@sha256:2ac3885612e2e5f3f59db987aa6d236f4fddc5d9dfe47d929739b26dc7c49ade
          name: backend-agent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: GOOGLE_CLOUD_PROJECT
              value: "alien-legacy-500702-r7"
          startupProbe:
            failureThreshold: 6
            periodSeconds: 10
            tcpSocket:
              port: 7668
            timeoutSeconds: 3

