/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125PublicRouteRouteImport } from './routes/{-$locale}/_public/route'
import { Route as Char123LocaleChar125PublicIndexRouteImport } from './routes/{-$locale}/_public/index'
import { Route as Char123LocaleChar125PublicLoginRouteImport } from './routes/{-$locale}/_public/login'
import { Route as Char123LocaleChar125PublicAboutRouteImport } from './routes/{-$locale}/_public/about'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125PublicRouteRoute =
  Char123LocaleChar125PublicRouteRouteImport.update({
    id: '/_public',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PublicIndexRoute =
  Char123LocaleChar125PublicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicLoginRoute =
  Char123LocaleChar125PublicLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)
const Char123LocaleChar125PublicAboutRoute =
  Char123LocaleChar125PublicAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/{-$locale}/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/login': typeof Char123LocaleChar125PublicLoginRoute
  '/{-$locale}/': typeof Char123LocaleChar125PublicIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125PublicIndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/{-$locale}/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/login': typeof Char123LocaleChar125PublicLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/{-$locale}/_public': typeof Char123LocaleChar125PublicRouteRouteWithChildren
  '/{-$locale}/_public/about': typeof Char123LocaleChar125PublicAboutRoute
  '/{-$locale}/_public/login': typeof Char123LocaleChar125PublicLoginRoute
  '/{-$locale}/_public/': typeof Char123LocaleChar125PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/chat'
    | '/dashboard'
    | '/{-$locale}/about'
    | '/{-$locale}/login'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/chat'
    | '/dashboard'
    | '/{-$locale}/about'
    | '/{-$locale}/login'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/chat'
    | '/dashboard'
    | '/{-$locale}/_public'
    | '/{-$locale}/_public/about'
    | '/{-$locale}/_public/login'
    | '/{-$locale}/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_public': {
      id: '/{-$locale}/_public'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125PublicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_public/': {
      id: '/{-$locale}/_public/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125PublicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/login': {
      id: '/{-$locale}/_public/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125PublicLoginRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
    '/{-$locale}/_public/about': {
      id: '/{-$locale}/_public/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125PublicAboutRouteImport
      parentRoute: typeof Char123LocaleChar125PublicRouteRoute
    }
  }
}

interface Char123LocaleChar125PublicRouteRouteChildren {
  Char123LocaleChar125PublicAboutRoute: typeof Char123LocaleChar125PublicAboutRoute
  Char123LocaleChar125PublicLoginRoute: typeof Char123LocaleChar125PublicLoginRoute
  Char123LocaleChar125PublicIndexRoute: typeof Char123LocaleChar125PublicIndexRoute
}

const Char123LocaleChar125PublicRouteRouteChildren: Char123LocaleChar125PublicRouteRouteChildren =
  {
    Char123LocaleChar125PublicAboutRoute: Char123LocaleChar125PublicAboutRoute,
    Char123LocaleChar125PublicLoginRoute: Char123LocaleChar125PublicLoginRoute,
    Char123LocaleChar125PublicIndexRoute: Char123LocaleChar125PublicIndexRoute,
  }

const Char123LocaleChar125PublicRouteRouteWithChildren =
  Char123LocaleChar125PublicRouteRoute._addFileChildren(
    Char123LocaleChar125PublicRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125PublicRouteRoute: typeof Char123LocaleChar125PublicRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125PublicRouteRoute:
      Char123LocaleChar125PublicRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
